
train:
  epochs: 100
  batch_size: 16
  val_epoch: 10
  save_epoch: 10

file:
  logdir: log/
  save_path: save/


data:
  standard: True
  name: 'cifar10'
  number: 1000

model:
  name: "stacked-unet"
  num_class: 10
  starter_lr: 0.0002
  decay_steps: 1000
  global_step: 100000
  inputs:
    x_pl:
      name: input
      shape: [32, 32, 3]
    y_pl:
      name: output
      shape: [1]