
train:
  epochs: 1000
  batch_size: 64
  val_epoch: 10
  save_epoch: 10

file:
  logdir: log/cifar10/
  save_path: save/cifar10/


data:
  name: 'cifar10'
  split_ratio: 0.8

model:
  name: "stacked-unet"
  num_class: 10
  starter_lr: 0.0001
  decay_steps: 1000
  global_step: 100
  inputs:
    x_pl:
      name: input
      shape: [32, 32, 3]
    y_pl:
      name: output
      shape: [1]