
train:
  epochs: 1000
  batch_size: 64
  val_epoch: 10
  save_epoch: 10

file:
  logdir: log/sunet-imagenet/
  save_path: save/sunet-imagenet/


data:
  standard: True
  name: 'ILSVRC2012'
  img_dir: '/home/ubuntu/Downloads/ILSVRC2012_img_train_t3'
  label_fp: '/home/ubuntu/Downloads/ILSVRC/devkit/data/map_clsloc.txt'
  extracted: True
  split_ratio: 0.8

model:
  name: "stacked-unet"
  num_class: 120
  starter_lr: 0.0002
  decay_steps: 1000
  global_step: 100
  inputs:
    x_pl:
      name: input
      shape: [224, 224, 3]
    y_pl:
      name: output
      shape: [1]